### ISSUE TITLE
Lids and Windows Attributes

### ISSUE THREAD

**Issue by lolouk44** [bimmerconnected/ha_custom_component#17]
I had issues connecting to bimmerconnected via HA (just had a power outage, no idea if related)
After a few reboots, HA finally managed to connect, but some of my template sensors failed.
looking into it the attributes for lids and windows had a change in name and case (e.g. doorDriverFront became driverFront)
I suspect this is a change on the API, yet can something be put in place to catter for this? Especially the change in case? I.e. can the attributes be forced to be in lower case so that if BMW changes something it does not impact the custom_component?

**Comment by rikroe** [comment]
Thanks for bringing this up! This attribute is rather stable on the BMW API and has only changed due to the complete redesign of the app. 

I would rather add this as breaking change & keep the default naming than manually adjusting it.

**Comment by lolouk44** [comment]
Happy with this approach, just didn't want it to change again for me to rewrite my templates 😉
