### ISSUE TITLE
Update to recent version - tracking disabled

### ISSUE THREAD

**Issue by MarcinL1977** [bimmerconnected/ha_custom_component#18]
Is there something needed on the configuration side of things to enable tracking back? I have updated custom component to the latest version in HACS an hour ago and lost tracking of vehicle. Below is the log from home assistant core. Before the update I had no issues with car position being updated

> 2021-12-04 14:22:58 INFO (MainThread) [custom_components.bmw_connected_drive.device_tracker] Tracking is (currently) disabled for vehicle X3 xDrive20d (VIN ...), defaulting to unknown

**Comment by rikroe** [comment]
Please provide a `fingerprint` of your vehicle. There were some recent changes but they didn't break anything in my tests.

**Comment by MarcinL1977** [comment]
Sure, atatched.

[vehicles_v2_bmw_0.txt](https://github.com/bimmerconnected/ha_custom_component/files/7655938/vehicles_v2_bmw_0.txt)

**Comment by epl2005** [comment]
I have the same issue here my fingerprint 
Thank you
[vehicles_v2_bmw_0.txt](https://github.com/bimmerconnected/ha_custom_component/files/7655955/vehicles_v2_bmw_0.txt)

**Comment by rikroe** [comment]
Oops, I updated the Python code for the custom component, but didn't specify to use the latest library version in the custom component. 

Please update and let me know if it is working again.

**Comment by MarcinL1977** [comment]
Works now! Let me use the opportunity to thank you for your time and effort you dedicate to have this working.

**Comment by epl2005** [comment]
> Oops, I updated the Python code for the custom component, but didn't specify to use the latest library version in the custom component.
> 
> Please update and let me know if it is working again.

It works also for me thank you very much
