### ISSUE TITLE
Wrong time format for charging_end_time_original

### ISSUE THREAD

**Issue by rhoddan** [bimmerconnected/ha_custom_component#19]
![Skärmavbild 2021-12-07 kl  21 29 19](https://user-images.githubusercontent.com/33499995/145101684-12f78e1d-e151-4d2b-93d1-9e1ac3afe7a2.png)

I'm using the 24h time format but "charging_end_time_original" gives 12h

**Comment by rikroe** [comment]
The `_original` sensor will always show whats extracted from BMW API and it is always in 12h format. This sensor therefore should only be used for debugging purposes.
`charging_end_time` (without `_original`) is the one that should be used.
