### ISSUE TITLE
entity lock/unlock not available after upgrade Home Assistant Core 2021.12.1 and Home Assistant Core 2021.12.2

### ISSUE THREAD

**Issue by claudiovillani58** [bimmerconnected/ha_custom_component#20]
Hello everyone following an upgrade of “Home Assistant Core 2021.12.0” to “Home Assistant Core 2021.12.1” and to "Home Assistant Core 2021.12.2" the key that I had previously worked for opening and closing doors of my “MINI Cooper S” now no longer works on the board is in the “Not Available” state, this key was referring to the entity: “lock.cooper_s_lock”. To make sure that with the release “Home Assistant Core 2021.12.0” it worked well I reloaded a backup and the key returned to work as I reinstalled the release Home Assistant Core 2021.12.1 it stopped working again making itself “Unavailable”. Could you help me understand? or to solve the problem?

**Comment by claudiovillani58** [comment]
Hello can you tell me why until a few days ago I could open and close my new type mini cooper with the lock / unlock button and today it no longer works. Can it be restored? another thing is it possible that you can make a change to know which door is open eg left door or right door or trunk or front hood are data that mini provides in its APP.
Thanks A greeting

**Comment by rikroe** [comment]
We didn't change anything after from 2021.12.0. Please provide any logs if available.

**Comment by rikroe** [comment]
Duplicate with #22

**Comment by claudiovillani58** [comment]
thank You
