### ISSUE TITLE
New entity

### ISSUE THREAD

**Issue by claudiovillani58** [bimmerconnected/ha_custom_component#21]
Hi it is possible to have new entities that can identify not in a generic way such as opening left door or opening right door, opening bonnet or trunk opening, opening left window or opening right window and again if the parking lights or other type of lights when the 'car is stationary are on or off, and possible other indications such as engine oil, brake fluid etc.
Thanks for the attention

**Comment by rikroe** [comment]
Currently the information for open windows & doors is available as attribute to the the `windows` or `lids` entities.
Also `check_control_message` like engine oil etc. are shown (however I think only if there critical/warning).

Do you also want to see these messages if everything is ok?
