### ISSUE TITLE
Fuel volume rounded to integer gallons - not very useful on i3 REX with tiny tank

### ISSUE THREAD

**Issue by progman32** [bimmerconnected/ha_custom_component#23]
Hi, thanks for this fantastic add on. I just installed it and am already using it to get universal charge status notifications that actually work consistently and aren't tied to a charge network. I'll also use it to manage my car's interaction with my future photovoltaic system, allowing more efficient use of surplus power. So cool.

One small issue using it with my i3 REX, which has a tiny fuel tank (even softmodded to allow using the entire thing). It appears this component rounds the fuel volume to the nearest whole gallon, which means my car either shows 2 gallons, 1 gallon, or empty. It would be great if folks using gallons could get one or two digits after the decimal. I see the underlying API provides decimal liters. Since a liter is about a quarter gallon, that's about four times the available resolution.

It appears the code in question is https://github.com/bimmerconnected/ha_custom_component/blob/9f17a77dad5dbad6f279439d90df1b15efddbd0a/custom_components/bmw_connected_drive/sensor.py#L110-L112

**Comment by rikroe** [comment]
Very good catch - that sound like an easy fix. Can you update line 111 in `sensor.py` and just add `, 2` (no other brackets etc. to the end?)

If that works for you, I'll create a PR to HA to have it included directly, without the need for a custom component.

**Comment by progman32** [comment]
Ah, I think I'm confused. I thought this was the place where development happened on the default integration. I'm not actually using the custom component. Let me set up a testing instance of HA and I'll give it a shot with the custom component.

**Comment by progman32** [comment]
![image](https://user-images.githubusercontent.com/48895/147030125-d2ef4f88-ce28-456d-b4f4-2d570bd3db58.png)
It works! `1.85 gal`!

**Comment by rikroe** [comment]
No worries! I'll think about adding a issue template, as it is actually confusing deciding between the Home Assistant repo for the default component, the bimmer connected repo for the background library and this.

Glad it worked, I've also created a PR with Home Assistant.

**Comment by rikroe** [comment]
Closing this as the code was merged with HA core and will be included in HA 2022.2.
