### ISSUE TITLE
Component could not be loaded

### ISSUE THREAD

**Issue by Pirol62** [bimmerconnected/ha_custom_component#29]
After loading down the new beta
````
Logger: homeassistant.setup
Source: setup.py:178
First occurred: 15:36:23 (1 occurrences)
Last logged: 15:36:23

Setup failed for bmw_connected_drive: Unable to import component: cannot import name 'Platform' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

````

**Comment by Pirol62** [comment]
Maybe this was due to the fact that I'm still on 2021.11.5. I rolled  back to the version before which brought back the authentication errors but a death must be died

**Comment by rikroe** [comment]
Yep, the latest version was based on 2021.12 where some constants got replaced by the HA team. Custom component 20211211.1 will be the last one that is compatible with 2021.11, but you could try to update the library version (see https://github.com/bimmerconnected/ha_custom_component/issues/29).
