### ISSUE TITLE
No attributes / states for some entities any more

### ISSUE THREAD

**Issue by arboeh** [bimmerconnected/ha_custom_component#34]
I don't recieve attributes for lock.i3s_120_lock and binary_sensor.i3s_120_condition_based_services any more. States "unknown" and "off" are shown as states now. Screenshots attached.
![2022-03-31 07_14_02-Window](https://user-images.githubusercontent.com/12322114/160981588-59804abe-eb40-423a-8785-df462710b63a.png)
![2022-03-31 07_12_56-Window](https://user-images.githubusercontent.com/12322114/160981592-5c593094-3990-466b-9c3b-5cf0e13aec05.png)
.

**Comment by arboeh** [comment]
There have been the attributes brake_fluid_date, vehicle_check_date and vehicle_tuv_date for me and there are no attributes any more.
Seems to be a problem with i3s_120_check_control_messages also. There have been detailed messages and now the state "off" is shown all the time.

**Comment by rikroe** [comment]
Could you please provide a fingerprint (`bimmerconnected fingerprint <username> <password> <region>` on the command line) so I can debug this a little more?

**Comment by arboeh** [comment]
[charging-sessions_0.txt](https://github.com/bimmerconnected/ha_custom_component/files/8400065/charging-sessions_0.txt)
[charging-statistics_0.txt](https://github.com/bimmerconnected/ha_custom_component/files/8400066/charging-statistics_0.txt)
[vehicles_v2_bmw_0.txt](https://github.com/bimmerconnected/ha_custom_component/files/8400067/vehicles_v2_bmw_0.txt)
[vehicles_v2_mini_0.txt](https://github.com/bimmerconnected/ha_custom_component/files/8400068/vehicles_v2_mini_0.txt)

**Comment by rikroe** [comment]
Thanks! Yeah, the API is a bit flaky. 

But I found the culprit, please try the latest release!

**Comment by arboeh** [comment]
Yup. Its working again. Thanks very much!
