### ISSUE TITLE
No fuel

### ISSUE THREAD

**Issue by rpimaster88** [bimmerconnected/ha_custom_component#36]
Hello, 
I have installed the latest Version and the Sensor range was not working. Then I reinstalled the latest Version and the 
Sensor (sensor.remaining_range_total) is not more in home assistant.

Home assistant: 2022.4.1
BMW 320d G21

Thanks.

**Comment by rikroe** [comment]
Hi, `remaining_range_total` was renamed to `remaining_range_combined` to be aligned with the upstream naming (see the [release notes](https://github.com/bimmerconnected/ha_custom_component/releases/tag/20220410.2) , they are visible from inside HACS as well). 
Please check if the new sensor is available to you.

**Comment by rikroe** [comment]
Please update to 20220410.3, that has reverted to `remaining_range_total`.

**Comment by rpimaster88** [comment]
Now it's working! Thank you.
