### ISSUE TITLE
sensor.charging_level_hv to sensor.remaining_battery_percent missing completely

### ISSUE THREAD

**Issue by rest77** [bimmerconnected/ha_custom_component#37]
The SOC for the HV battery is missing even in the last update 20220410.3

**Comment by rikroe** [comment]
Thanks for the report! Should be fixed with 20221004.4.

**Comment by pnarest** [comment]
It works again! Thanks a lot for your great contribution!

**Comment by rest77** [comment]
It works again! Thanks a lot for your great contribution!
