### ISSUE TITLE
No charging level any more

### ISSUE THREAD

**Issue by arboeh** [bimmerconnected/ha_custom_component#38]
Since update to latets version there is no charging level for me any more... It worked before.

![2022-04-11 06_28_48-Window](https://user-images.githubusercontent.com/12322114/162666648-e60a9713-4c4f-4724-bf3c-9a7b6673eef9.png)

**Comment by rest77** [comment]
See release notes:

Renamed sensors to streamline them:
sensor.charging_level_hv to sensor.remaining_battery_percent

**Comment by arboeh** [comment]
Oh, sorry. Okay. Thanks anyway.

**Comment by rikroe** [comment]
No worries! Thanks for being beta testers :)
