### ISSUE TITLE
Sensor showing "unknown" oder "unbekannt" if Battery Level or electric range level is 0

### ISSUE THREAD

**Issue by mibo-wb-gh** [bimmerconnected/ha_custom_component#41]
the following sensors:
sensor.330e_xdrive_remaining_range_electric
sensor.330e_xdrive_remaining_battery_percent

show "Unbekannt" or probably "Unkown" if the remaining electric range is 0km 

or the 

remaining battery percentage is 0%

Running Home Assistant 2022.3.8 / HACS BMW Connected Drive Custom Component 20220410.4

**Comment by rikroe** [comment]
Could you please provide a fingerprint if your battery is at 0 percent? Curious how BMW is returning these values.

**Comment by mibo-wb-gh** [comment]
Unfortunately since last year when there was the major rework, I am no longer able to upgrade bimmer_connected so I can provide you with a fingerprint. It always runs into a problem regarding pycryptodome an gcc, which probably are error dependencies, Please find a screenshot attached. I already tried different solution, but none have had any effect on this error.

Running on python 3.9

![image](https://user-images.githubusercontent.com/87424844/163356787-c9adc2ec-3ad0-46ee-8224-77790c92bb5f.png)

**Comment by rikroe** [comment]
Apparently, you have to install some linux packages to be able to install pycryptodome...
Please try `sudo apt-get install build-essential python3-dev` (for Ubuntu) before installing bimmer-connected.

**Comment by mibo-wb-gh** [comment]
Thx. I will have to setup homeassistant on a different base. (Ubuntu or Debian) I will get back to you.

**Comment by rikroe** [comment]
Whats the OS you're using? Otherwise check https://pycryptodome.readthedocs.io/en/latest/src/installation.html

**Comment by rikroe** [comment]
Please check 20220415.1 if that is solving your issues!
