### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by sonsornpan** [bimmerconnected/ha_custom_component#43]
BMW Connected Drive Custom Component for Development v.20220529.1
with Home Assistant 2021.11.5

After adding a custom component with HACs , restart HA.
then Set up a new integration, BMW Connected Drive.

"Error
Config flow could not be loaded"

How to solve this problem?

Thank you so much.

**Comment by rikroe** [comment]
There might have been changes in the HA backend, that the latest version relies on. The component is only tested to work with 2022.4 + above.

Any error message in the logs?

**Comment by sonsornpan** [comment]
No error in logs.

New version of HA have some problem with my devices, I have to use this version.

Thank you.

**Comment by rikroe** [comment]
I can try to have a look this evening. But I am pretty sure that at least Sensors + Binary Sensors won't work with 2021.11 due to HA backend changes in 2022.2. Sorry :(

**Comment by sonsornpan** [comment]
ver.0.8.7.0b1 worked until 29May2022 , now it is unavailable.
![bimmer](https://user-images.githubusercontent.com/89729452/171380285-ed905f94-7346-4b3f-894b-a70fff5d6b9a.jpg)
