### ISSUE TITLE
error connecting to account

### ISSUE THREAD

**Issue by marcoevcom** [bimmerconnected/ha_custom_component#45]
This event log started showing up a few days ago, I tried removing the integration and when I add again it won't authenticate.

Logger: homeassistant.config_entries
Source: config_entries.py:370
First occurred: June 2, 2022, 7:00:27 PM (1 occurrences)
Last logged: June 2, 2022, 7:00:27 PM

Config entry xxxx@vxxxi.com.br' for bmw_connected_drive integration not ready yet: Error communicating with API: Client error '403 Forbidden' for url 'https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config' For more information check: https://httpstatuses.com/403; Retrying in background

**Comment by rikroe** [comment]
Are you on the latest custom component via HACS or on 2022.6? Should be fixed there.

**Comment by max-men-cat** [comment]
I can't login either.  I'm using the latest version, downloaded by HACS
![image](https://user-images.githubusercontent.com/69223245/172153626-df19f711-fa2d-489d-b350-2af2cfcbf5f9.png)

![image](https://user-images.githubusercontent.com/69223245/172153682-bf541bc0-e591-41cb-b8d8-62ce6084ebb7.png)

**Comment by marcoevcom** [comment]
This problem was solved after updating HA with the newer version: Core 2022.6.2, Supervisor 2022.05.3 
I never tried with the beta version.

**Comment by max-men-cat** [comment]
I still can't log in.  I have everything updated

**Comment by rikroe** [comment]
If you still have issues, please try the following:
- Remove or deactivate the BMW Connected Drive integration from Home Assistant
- Wait at least 1 hour
- Add the integration again

If that doesn't work, please double check the logs if there is anything that gives you a hint. Worst case, please add or adjust the `logging` section in your `configuration.yaml`:
```yaml
logger:
  default: info
  logs:
    homeassistant.components.bmw_connected_drive: debug
    custom_components.bmw_connected_drive: debug
    bimmer_connected: debug
    httpx: debug
```

This will print a lot of lines to your log (use the the "show full log" functionality) but might give a better indication whats going wrong.
