### ISSUE TITLE
Failure - Option "near"

### ISSUE THREAD

**Issue by Maxi2509** [bimmerconnected/ha_custom_component#46]
Hi,

i am no expert in this but i get every day this failure in my logs and i am not able to find the problem. Can somebody please help?
Integration works well for me but i want to remove this failure.

### Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bmw_connected_drive
Source: helpers/config_validation.py:831
Integration: BMW Connected Drive
First occurred: 08:09:18 (1 occurrences)
Last logged: 08:09:18

The 'bmw_connected_drive' option near /config/configuration.yaml:2 has been removed, please remove it from your configuration

![image](https://user-images.githubusercontent.com/77342189/173007606-968b624d-a433-43f4-8baf-4e6412a368ae.png)

### At the moment i am using:
Rasperry PI 4 - 32 bit

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

Best regards,
Maxi

**Comment by rikroe** [comment]
The reason is that you have a `bmw_connected_drive` entry in your HomeAssistant's `configuration.yaml`. You need to delete this entry (which has been migrated and therefore continues to work).

**Comment by Maxi2509** [comment]
thank you very much for your fast support. This solved everything :)
