### ISSUE TITLE
Auth problem again

### ISSUE THREAD

**Issue by nottledim** [bimmerconnected/ha_custom_component#51]
For the last few days I've been getting these errors:
```
 Error communicating with BMW API: Client error '400 Bad Request' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1657880993470&tireGuardMode=ENABLED'
```
Error started happening shortly after I updated core to 2022.7.3 but it did work initially so I don't think the update is necessarily  the problem.

I've seen similar error last for a few hours from time to time before but they go away suggesting they are caused by activity at BMW.

**Comment by rikroe** [comment]
You are most likely on an older version of the custom component. Please update (or delete the component. The HA stock component has the necessary changes for this since 2022.7.0.

**Comment by nottledim** [comment]
I just discovered that literally 5 mins ago. I've updated and yes it works.  Thanks for fixing that - much appreciated.
