### ISSUE TITLE
20220716.1 Forces metric units?

### ISSUE THREAD

**Issue by kcm117** [bimmerconnected/ha_custom_component#52]
Does version 20220716.1 now force metric units without any user configuration or option for imperial units?  Sensors with Miles and gallons have now changed to Kilometers and Liters.

This can have unintended consequences for those with automations and other logic tied to these sensors. Having the integration pull units preference from HA settings or having it configurable on the integration would be a more user friendly option.

**Comment by rikroe** [comment]
The integration used to retrieve the preferred units from HA and forwarded them to BMW. However something broke (poresumably on BMW side), and we changed it to always use metric values (in hope that HA's unit conversion will do the trick).
https://github.com/home-assistant/core/issues/75223

**Comment by kcm117** [comment]
It's now resolved after that commit!
