### ISSUE TITLE
Integration not loaded 

### ISSUE THREAD

**Issue by jonwilliams84** [bimmerconnected/ha_custom_component#63]
Just updated to 230503.1 and the integration no longer loads. I have tried deleting and re-downloading but now when I try to re-add the integration I get:
Error
Config flow could not be loaded: {"error":true,"code":"404","message":"Not Found","description":"The server can not find the requested page"}

**Comment by jonwilliams84** [comment]
From log:
Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 23:58:25 (1 occurrences)
Last logged: 23:58:25

Error occurred loading flow for integration bmw_connected_drive: cannot import name 'MyBMWAPIError' from 'bimmer_connected.models' (/config/deps/lib/python3.10/site-packages/bimmer_connected/models.py)

**Comment by rikroe** [comment]
I don't have that issue. Have you tried restarting your HA again?
I'm running HA 2023.5.0 and 20230503.1.

**Comment by jonwilliams84** [comment]
Yeah, tried several restarts. My HA version is 2023.5.1.

I have reverted to the old version of the integration and all is well again.

I will try another update at some point.

**Comment by rikroe** [comment]
Please try with 20230506.1 again. Maybe the error came from there somewhere.

**Comment by jonwilliams84** [comment]
> Please try with 20230506.1 again. Maybe the error came from there somewhere.

Yep - this did the trick. All working again. Thank you
