### ISSUE TITLE
Error raised during restart of HA

### ISSUE THREAD

**Issue by Pirol62** [bimmerconnected/ha_custom_component#70]
This error raised during restart. The component seems to work anyway afterwords regardless that error:
````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: bimmer_connected.api.authentication
Source: custom_components/bmw_connected_drive/coordinator.py:61
Integration: BMW Connected Drive
First occurred: 16:46:32 (2 occurrences)
Last logged: 16:46:45

MyBMW API error: HTTPStatusError: invalid_request - The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed
````

The integration config shows this picture:
![image](https://github.com/bimmerconnected/ha_custom_component/assets/48820003/b077a29e-6a5b-4c79-9a54-f5047569f2cc)

What's wrong?

**Comment by rikroe** [comment]
There were some API issues and for many users a password change was required on the MyBMW website (not app).

Anyways, please go back to the component shipped with Home Assistant, as the custom component is not updated currently.

**Comment by Pirol62** [comment]
HI @rikroe  In the integreations section only the custom component is available. 
There is no core component in the list.
I'm on 2023.7.3. Will ist come with 2023.8.x?

**Comment by rikroe** [comment]
No, you have to remove the custom component. It is a drop in replacement for the core component and will replace it.
