### ISSUE TITLE
Issue to login at service

### ISSUE THREAD

**Issue by jhalldn** [bimmerconnected/ha_custom_component#73]
Username/Password is checked and the addon has been deleted and reinstall without progress nor luck.

Logger: bimmer_connected.api.authentication
Source: components/bmw_connected_drive/config_flow.py:44
First occurred: 25 november 2023 21:25:27 (4 occurrences)
Last logged: 16:25:45

MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

**Comment by rikroe** [comment]
Please do not use the custom component anymore - it is outdated. Instead, use the version integrated to Home Assistant.
Also, you might have to wait until midnight UTC for a login failed quota to reset, so please be patient (and keep the integration disabled over midnight if it soesn't work directly).

**Comment by jhalldn** [comment]
Check for using the integrate version. That's the one im using with no luck of getting the login work. Have waited for more then 24h.

**Comment by rikroe** [comment]
Then please try logging in to the MyBMW website. We had issues in the past where the password had to be changed on the website, but the MyBMW app continued to work.

**Comment by jhalldn** [comment]
Good idea! I did login in with my U/P without issues at website. Anywho - I reset the P and retried from HA - it worked. Thanks for guidelines 🙏
