### ISSUE TITLE
Need to reconfigure addon DAILY

### ISSUE THREAD

**Issue by iz3man** [bimmerconnected/ha_custom_component#74]
For one week or so, the integrations becomes unavailable and I need to reconfgure it. It's just clicking through the dialogue and it's working again. 

```
Unexpected error fetching bmw_connected_drive-xxxxxxxxxxxxxxxxxx data: 'capabilities'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bmw_connected_drive/coordinator.py", line 61, in _async_update_data
    await self.account.get_vehicles()
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/account.py", line 113, in get_vehicles
    if vehicle_state[ATTR_CAPABILITIES].get("isChargingPlanSupported", False) or vehicle_state[
       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'capabilities'
```

20s later

`MyBMW API error: HTTPStatusError: { "statusCode": 429, "message": "Rate limit is exceeded. Try again in 1 seconds." }
MyBMW API error: HTTPStatusError: Client error '401 Unauthorized' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=60.0&appDateTime=1701088059022' For more information check: https://httpstatuses.com/401`

and this 

`Authentication failed while fetching bmw_connected_drive-xxxxxxxxxxxxxxx data: HTTPStatusError: Client error '401 Unauthorized' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=60.0&appDateTime=1701088059022' For more information check: https://httpstatuses.com/401`

Seems like there was some kind of RATE LIMIT introduced by BMW lately? But it's nothing under my control it seems?!

**Comment by 35aportal** [comment]
I have the same issue with the first the notification that an integration needs attention and then the reconfiguration process.  Following other comments on this issue, I deleted my HACS based integration and reinstalled the core HA integration, but still the same need to frequently reconfigure.

**Comment by rikroe** [comment]
No, there seem to be some changes on BMW side. However I have not fully understood how the API now works.

Please see https://github.com/home-assistant/core/issues/104555 and discuss there.

**Comment by iz3man** [comment]
Maybe someone can help me, but all my ACTIVE service requests are missing for some time now. I can't say when they vanished, as I use only AUXILIARY HEATING, and only in winter, so I didn't check that for a while.
All sensors are here, like charging state, range, open windows etc, but not those SWITCHES where you could control the car.
Thanks
