### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by simon6661** [bimmerconnected/ha_custom_component#76]
![微信图片_20240308211633](https://github.com/bimmerconnected/ha_custom_component/assets/64183045/8989cd94-9e5a-40cb-a3e0-17b3f7dfbbcc)

connect failed

Home Assistant  Core 2024.3.0

**Comment by Captain0Kangaroo** [comment]
> ![微信图片_20240308211633](https://private-user-images.githubusercontent.com/64183045/311245079-8989cd94-9e5a-40cb-a3e0-17b3f7dfbbcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTg0OTEsIm5iZiI6MTcwOTkxODE5MSwicGF0aCI6Ii82NDE4MzA0NS8zMTEyNDUwNzktODk4OWNkOTQtOWU1YS00MGNiLWEzZTAtMTdiM2Y3ZGZiYmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3MTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MTNmYzBjODUyYzQ5N2E0NjZhOGRkMGZkZTJlMGU4MTEyNzRhN2E4MWMxYTY3OTdiNWIzMjQyMTJlYWRkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lW3_dioJWqlYda2UCYgRn1xgie0h_6CWGSau8cYRN3Q)
> 
> connect failed
> 
> Home Assistant Core 2024.3.0

Try rest_of_world. Worked for me today.

**Comment by rikroe** [comment]
China login is unfortunately broken https://github.com/bimmerconnected/bimmer_connected/issues/588 right now.

**Comment by simon6661** [comment]
Can the login be repaired?

Richard Kroegel ***@***.***> 于2024年3月9日周六 03:59写道：
