### ISSUE TITLE
BMW Ride Connect 

### ISSUE THREAD

**Issue by JStaegerino** [bimmerconnected/ha_custom_component#78]
Hello together

I was wondering if it is also possible to create an integration for BMW motorcycles. Unfortunately I have no idea about programming and the rest of the API. 
Basically there are only a few entities, but they would be very helpful:

- km status
- trip
- fuel 
- Rear tire pressure
- Front tire pressure
- Service in km and date

Perhaps one of you has an idea how this can be realized.

Thanks for your time
Best regards
Jan

**Comment by rikroe** [comment]
As far as we know, BMW motorcycles use a completely different backend than cars (which is shared between Mini and BMW).

So it is jot easily done and probably requires a completely separate library.

**Comment by JStaegerino** [comment]
All right, too bad to hear. Thanks anyway!
