### ISSUE TITLE
No Link for Captcha  available

### ISSUE THREAD

**Issue by thartlieb** [bimmerconnected/ha_custom_component#82]
hi, there is no link available in the popup for entering Captcha token.
Tested with Safari & Chrome.
Whats wrong with it?
redards
Torsten

**Comment by rikroe** [comment]
Try force reloading your browser cache if your on the latest custom component version.

Other than that, it's best to delete the custom component completely and use the one built in to HA.

**Comment by thartlieb** [comment]
works again with standard integration in Version 2024.0.1

**Comment by thartlieb** [comment]
closed
